# Generated by Django 4.1 on 2023-03-06 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='Date doit être sup à date sys',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('event_date__gte', datetime.datetime(2023, 3, 6, 11, 16, 57, 872916))), name='Date doit être sup à date sys'),
        ),
    ]
